### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by hpliner** [bbi-lab/bbi-dmux#18]
Had to reinstall some stuff so using the opportunity to test the install instructions:

git/2.19.1 didn't exist for me, had to use git/2.18.0 - to investigate

**Comment by hpliner** [comment]
Also needed 
pip install --user matplotlib
And
Garnett installed

**Comment by hpliner** [comment]
And scrublet (sync with one on bbi-sci?)

**Comment by aishwaryagogate** [comment]
Updated git/2.19.1 to git/2.18.0
Added matplotlib & scipy installation info
Added scrublet & Garnett installation info

All synced up with bbi-sci now!
